#! /usr/bin/env php

<?php

use therealsmat\ListCommand;
use therealsmat\NewApacheSiteCommand;
use therealsmat\NewNginxSiteCommand;
use therealsmat\NewSiteCommand;
use therealsmat\DeleteSiteCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application("PHP console tool for managing virtual hosts", "1.0");
$app->add(new ListCommand);
$app->add(new NewSiteCommand);
$app->add(new NewApacheSiteCommand());
$app->add(new NewNginxSiteCommand());
$app->add(new DeleteSiteCommand);
$app->run();
